library(shinytest2)


test_that("{shinytest2} recording: surveyDashboard_builtin - check maps", {
  local_app_support(test_path("apps/surveyDashboard_builtin"))
  app <- AppDriver$new(test_path("apps/surveyDashboard_builtin"), name = "surveyDashboard_builtin - check maps", 
      height = 949, width = 1619)
  app$set_inputs(sidebarItemExpanded = "Tables")
  app$set_inputs(sidebarItemExpanded = "Maps")
  app$set_inputs(scale_size = FALSE)
  app$set_inputs(scale_size = TRUE)
  app$set_inputs(no_record_more_transparent = FALSE)
  app$set_inputs(no_record_more_transparent = TRUE)
  app$set_inputs(species_for_map = "EGY")
  app$set_inputs(no_record_more_transparent = FALSE)
  app$set_inputs(species_for_map = "TRA")
  app$set_inputs(no_record_more_transparent = TRUE)
  app$set_inputs(no_record_more_transparent = FALSE)
  app$set_inputs(species_for_map = "MNE")
  app$set_inputs(scale_size = FALSE)
  app$set_inputs(no_record_more_transparent = TRUE)
  app$set_inputs(no_record_more_transparent = FALSE)
  app$set_inputs(scale_size = TRUE)
  app$set_inputs(scale_size = FALSE)
  app$set_inputs(scale_size = TRUE)
  app$set_inputs(scale_size = FALSE)
  app$set_inputs(scale_size = TRUE)
  app$set_inputs(no_record_more_transparent = TRUE)
  app$set_inputs(species_for_map = "EGY")
  app$set_inputs(scale_size = FALSE)
  app$set_inputs(scale_size = TRUE)
  app$set_inputs(no_record_more_transparent = FALSE)
  app$set_inputs(no_record_more_transparent = TRUE)
  app$set_inputs(scale_size = FALSE)
  app$expect_values()
})
